#!/bin/sh

DIRNAME="$HOME"/Library/Application\ Support/ezQuake

if [ ! -f "$DIRNAME"/id1/pak0.pak ]; then
    mkdir -p "$DIRNAME"/id1
    touch "$DIRNAME"/id1/Copy\ your\ pak0.pak\ and\ pak1.pak\ files\ here.txt
    osascript -e "tell app \"Finder\" to open (\"${DIRNAME}/id1/\" as POSIX file)"
    osascript -e "tell app \"Finder\" to activate"
    exit
fi

PNAME="$(dirname "$BASH_SOURCE")"

exec "$PNAME"/ezquake-darwin-arm -basedir "$DIRNAME" $*
