#!/bin/sh

PNAME="$(dirname "$BASH_SOURCE")"
DIRNAME="$HOME"/Library/Application\ Support/ezQuake
DIRNAME2="$PNAME"/../../..

if [ -f "$DIRNAME"/id1/pak0.pak ]; then
    exec "$PNAME"/ezquake-darwin-x86_64 -basedir "$DIRNAME" $*
elif [ -f "$DIRNAME2"/id1/pak0.pak ]; then
    exec "$PNAME"/ezquake-darwin-x86_64 -basedir "$DIRNAME2" $*
else
    mkdir -p "$DIRNAME"/id1
    touch "$DIRNAME"/id1/Copy\ your\ pak0.pak\ and\ pak1.pak\ files\ here.txt
    osascript -e "tell app \"Finder\" to open (\"${DIRNAME}/id1/\" as POSIX file)"
    osascript -e "tell app \"Finder\" to activate"
fi
